### ISSUE TITLE
issue when opening app after install

### ISSUE THREAD

**Issue by golgotow** [tailscale/tailscale-qpkg#69]
Hello,

I did build latest version Tailscale_1.34.2-1_x86_64.qpkg and install, when I try to open it via qnap portal is getting me to page with error

Get "https://127.0.0.1:443/cgi-bin/authLogin.cgi?sid=k0gygokg": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

How i Can troubleshoot ?

Best regards

**Comment by DentonGentry** [comment]
Are you using `tailscale up` from the CLI? The latest release is 1.34.1: https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.34.1

--------

The packages marked pre-release and named qnap-* are for the QNAP Package Center. If you've manually installed those and are trying to click the Tailscale icon to authenticate: in the Control Panel > General Settings do you have "Force secure connection (HTTPS) only" checked? That doesn't currently work, QNAP only has a self-signed certificate but then forces it to be used. The issue is tracked in https://github.com/tailscale/tailscale/issues/6903

**Comment by DentonGentry** [comment]
We will try to get the package into the AppCenter. We do not have a schedule of when that might happen.

**Comment by golgotow** [comment]
@ulfklose thanks you for checking it also, this work when I turn off this ssl ...
